import { Question, GameCategory } from '../types/game';

export const QUESTIONS: Question[] = [
  // ==========================================
  // MINI-GAME 1: COUNTRY QUIZ
  // ==========================================
  {
    id: 'cq-1',
    category: 'country_quiz',
    countryCode: 'TN',
    countryName: 'Tunisia',
    difficulty: 'easy',
    prompt: 'Which country is home to the stunning blue-and-white clifftop village of Sidi Bou Said and ancient Carthage?',
    options: ['Tunisia', 'Greece', 'Morocco', 'Portugal'],
    correctAnswer: 'Tunisia',
    explanation: 'Sidi Bou Said sits perched above the Mediterranean in Tunisia, famed for its cobalt doors, vibrant bougainvillea, and proximity to Carthage.',
    active: true,
  },
  {
    id: 'cq-2',
    category: 'country_quiz',
    countryCode: 'JP',
    countryName: 'Japan',
    difficulty: 'easy',
    prompt: 'Which island nation features Mount Fuji and consists of four main islands: Honshu, Hokkaido, Kyushu, and Shikoku?',
    options: ['South Korea', 'Japan', 'Philippines', 'Indonesia'],
    correctAnswer: 'Japan',
    explanation: 'Mount Fuji is an iconic active stratovolcano and sacred mountain on Honshu island in Japan.',
    active: true,
  },
  {
    id: 'cq-3',
    category: 'country_quiz',
    countryCode: 'FR',
    countryName: 'France',
    difficulty: 'easy',
    prompt: 'Which European country is often geographically referred to as "L\'Hexagone" (The Hexagon)?',
    options: ['Germany', 'France', 'Spain', 'Italy'],
    correctAnswer: 'France',
    explanation: 'Because mainland France roughly resembles a six-sided geometric figure, it is affectionately nicknamed "l’Hexagone".',
    active: true,
  },
  {
    id: 'cq-4',
    category: 'country_quiz',
    countryCode: 'BR',
    countryName: 'Brazil',
    difficulty: 'easy',
    prompt: 'What is the official capital city of Brazil?',
    options: ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'],
    correctAnswer: 'Brasília',
    explanation: 'While Rio and São Paulo are famous worldwide, Brasília has been the planned federal capital of Brazil since 1960.',
    active: true,
  },
  {
    id: 'cq-5',
    category: 'country_quiz',
    countryCode: 'EG',
    countryName: 'Egypt',
    difficulty: 'easy',
    prompt: 'Which country features the Great Sphinx and the Pyramids along the banks of the Nile?',
    options: ['Sudan', 'Jordan', 'Egypt', 'Iraq'],
    correctAnswer: 'Egypt',
    explanation: 'The Giza pyramid complex and the Great Sphinx are located on the Giza Plateau outside Cairo, Egypt.',
    active: true,
  },
  {
    id: 'cq-6',
    category: 'country_quiz',
    countryCode: 'KR',
    countryName: 'South Korea',
    difficulty: 'medium',
    prompt: 'King Sejong the Great invented which unique writing system in the 15th century to increase literacy?',
    options: ['Hangul', 'Kanji', 'Pinyin', 'Katakana'],
    correctAnswer: 'Hangul',
    explanation: 'Hangul was deliberately crafted in 1443 under King Sejong so that all Korean citizens could learn to read and write easily.',
    active: true,
  },
  {
    id: 'cq-7',
    category: 'country_quiz',
    countryCode: 'MA',
    countryName: 'Morocco',
    difficulty: 'medium',
    prompt: 'Which Moroccan mountain town is globally celebrated as the "Blue Pearl" for its blue-washed buildings?',
    options: ['Marrakech', 'Chefchaouen', 'Casablanca', 'Tangier'],
    correctAnswer: 'Chefchaouen',
    explanation: 'Chefchaouen is nestled in the Rif mountains and attracts visitors worldwide with its striking cobalt and sky-blue alleyways.',
    active: true,
  },
  {
    id: 'cq-8',
    category: 'country_quiz',
    countryCode: 'AU',
    countryName: 'Australia',
    difficulty: 'easy',
    prompt: 'Which country is both a sovereign nation and its own distinct continent?',
    options: ['New Zealand', 'Australia', 'Madagascar', 'Greenland'],
    correctAnswer: 'Australia',
    explanation: 'Australia is uniquely classified as the smallest continental landmass and the sixth largest country in the world.',
    active: true,
  },
  {
    id: 'cq-9',
    category: 'country_quiz',
    countryCode: 'IT',
    countryName: 'Italy',
    difficulty: 'easy',
    prompt: 'Which country surrounds two independent sovereign enclaves: San Marino and Vatican City?',
    options: ['Switzerland', 'Italy', 'France', 'Austria'],
    correctAnswer: 'Italy',
    explanation: 'Both Vatican City and San Marino are entirely surrounded within the geographic borders of Italy.',
    active: true,
  },
  {
    id: 'cq-10',
    category: 'country_quiz',
    countryCode: 'PE',
    countryName: 'Peru',
    difficulty: 'medium',
    prompt: 'The ancient 15th-century Inca sanctuary of Machu Picchu is located in which South American nation?',
    options: ['Bolivia', 'Chile', 'Peru', 'Ecuador'],
    correctAnswer: 'Peru',
    explanation: 'Machu Picchu is set high in the Andes mountains above the Urubamba River valley in Peru.',
    active: true,
  },
  {
    id: 'cq-11',
    category: 'country_quiz',
    countryCode: 'CA',
    countryName: 'Canada',
    difficulty: 'medium',
    prompt: 'Which country has the longest coastline in the world and produces over 70% of the globe\'s pure maple syrup?',
    options: ['Canada', 'Norway', 'Russia', 'Sweden'],
    correctAnswer: 'Canada',
    explanation: 'Canada boasts 243,042 km of coastline, and Quebec alone produces the majority of the world’s pure maple syrup.',
    active: true,
  },
  {
    id: 'cq-12',
    category: 'country_quiz',
    countryCode: 'MX',
    countryName: 'Mexico',
    difficulty: 'easy',
    prompt: 'The Mayan pyramid of El Castillo (Kukulkan Temple) at Chichen Itza is located in which country?',
    options: ['Guatemala', 'Mexico', 'Honduras', 'Belize'],
    correctAnswer: 'Mexico',
    explanation: 'Chichen Itza is situated in the Yucatan Peninsula of Mexico and is named one of the New Seven Wonders of the World.',
    active: true,
  },
  {
    id: 'cq-13',
    category: 'country_quiz',
    countryCode: 'DE',
    countryName: 'Germany',
    difficulty: 'medium',
    prompt: 'Which fairytale 19th-century Romanesque Revival castle in Bavaria inspired the iconic Disney castle?',
    options: ['Neuschwanstein Castle', 'Hohenzollern Castle', 'Heidelberg Castle', 'Eltz Castle'],
    correctAnswer: 'Neuschwanstein Castle',
    explanation: 'Neuschwanstein Castle, commissioned by King Ludwig II of Bavaria, was the primary inspiration for Disney’s Sleeping Beauty Castle.',
    active: true,
  },
  {
    id: 'cq-14',
    category: 'country_quiz',
    countryCode: 'IN',
    countryName: 'India',
    difficulty: 'easy',
    prompt: 'Which country is home to the ivory-white marble mausoleum Taj Mahal on the bank of the Yamuna River?',
    options: ['Pakistan', 'India', 'Bangladesh', 'Nepal'],
    correctAnswer: 'India',
    explanation: 'The Taj Mahal in Agra, India was commissioned in 1632 by Mughal Emperor Shah Jahan.',
    active: true,
  },
  {
    id: 'cq-15',
    category: 'country_quiz',
    countryCode: 'NO',
    countryName: 'Norway',
    difficulty: 'medium',
    prompt: 'Which Scandinavian country is famous for the breathtaking Geirangerfjord and the Arctic Svalbard Global Seed Vault?',
    options: ['Finland', 'Denmark', 'Norway', 'Iceland'],
    correctAnswer: 'Norway',
    explanation: 'Norway is renowned for its dramatic glacial fjords and preserves biodiversity via the Svalbard Seed Vault.',
    active: true,
  },

  // ==========================================
  // MINI-GAME 2: GUESS THE WORD
  // ==========================================
  {
    id: 'gw-1',
    category: 'guess_word',
    countryCode: 'TN',
    countryName: 'Tunisia',
    difficulty: 'easy',
    prompt: 'In Tunisian Arabic (Darija), what does the ubiquitous word "برشا" (Barsha / Barcha) mean?',
    options: ['A lot / Very much', 'Thank you', 'Delicious food', 'Goodbye'],
    correctAnswer: 'A lot / Very much',
    explanation: '"Barsha" (برشا) is one of the most famous Tunisian words, meaning "a lot", "very", or "plenty" (e.g., "Nhebbek barsha" = I love you very much)!',
    active: true,
  },
  {
    id: 'gw-2',
    category: 'guess_word',
    countryCode: 'JP',
    countryName: 'Japan',
    difficulty: 'medium',
    prompt: 'In Japanese, what poetic phenomenon does the word "木漏れ日" (Komorebi) describe?',
    options: ['Sunlight filtering through tree leaves', 'The smell of fresh rain', 'Winter snow melting', 'A sudden gust of sea wind'],
    correctAnswer: 'Sunlight filtering through tree leaves',
    explanation: '"Komorebi" (木漏れ日) beautifully captures the dappled sunlight filtering through tree branches and leaves.',
    active: true,
  },
  {
    id: 'gw-3',
    category: 'guess_word',
    countryCode: 'BR',
    countryName: 'Brazil',
    difficulty: 'medium',
    prompt: 'In Portuguese (prominently in Brazil), what does the deeply emotional untranslatable word "Saudade" express?',
    options: ['A profound longing/nostalgia for someone or something beloved', 'Bursting joyful laughter', 'Good fortune in travel', 'A festive celebration with dance'],
    correctAnswer: 'A profound longing/nostalgia for someone or something beloved',
    explanation: '"Saudade" captures a melancholic yearning for a person, place, or memory that is dearly missed.',
    active: true,
  },
  {
    id: 'gw-4',
    category: 'guess_word',
    countryCode: 'FR',
    countryName: 'France',
    difficulty: 'medium',
    prompt: 'In French, what feeling does the word "Dépaysement" denote?',
    options: ['The disorienting or exhilarating feeling of being in a foreign land', 'Homesickness after long journeys', 'A pleasant afternoon picnic', 'A delicious culinary revelation'],
    correctAnswer: 'The disorienting or exhilarating feeling of being in a foreign land',
    explanation: '"Dépaysement" describes the sensation of stepping outside your comfort zone into a refreshingly unfamiliar culture.',
    active: true,
  },
  {
    id: 'gw-5',
    category: 'guess_word',
    countryCode: 'ES',
    countryName: 'Spain',
    difficulty: 'easy',
    prompt: 'In Spanish culture, what does the beloved tradition of "Sobremesa" mean?',
    options: ['Linger at the table conversing after finishing a meal', 'A dessert served before main courses', 'Setting a colorful dinner table', 'A quick nap on a sofa'],
    correctAnswer: 'Linger at the table conversing after finishing a meal',
    explanation: '"Sobremesa" is the time spent relaxing and chatting with friends and family around the dinner table long after dessert.',
    active: true,
  },
  {
    id: 'gw-6',
    category: 'guess_word',
    countryCode: 'DE',
    countryName: 'Germany',
    difficulty: 'medium',
    prompt: 'In German, what warm atmospheric state is described by "Gemütlichkeit"?',
    options: ['Cozy, warm, and friendly social comfort', 'Strict punctuality and order', 'A long hike across mountains', 'A sudden burst of creative genius'],
    correctAnswer: 'Cozy, warm, and friendly social comfort',
    explanation: '"Gemütlichkeit" describes a state of warmth, friendliness, good cheer, and peace of mind.',
    active: true,
  },
  {
    id: 'gw-7',
    category: 'guess_word',
    countryCode: 'IT',
    countryName: 'Italy',
    difficulty: 'easy',
    prompt: 'In Italian everyday conversation, accompanied by a shoulder shrug, what does "Boh!" express?',
    options: ['"I don\'t know!" / "Who knows?"', '"Watch out!"', '"Delicious!"', '"Hello my friend!"'],
    correctAnswer: '"I don\'t know!" / "Who knows?"',
    explanation: '"Boh!" is an expressive Italian vocalization meaning "I have no clue!" or "Who knows?".',
    active: true,
  },
  {
    id: 'gw-8',
    category: 'guess_word',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    difficulty: 'medium',
    prompt: 'In Wales (Welsh culture), what does the cherished word "Cwtch" signify?',
    options: ['A loving, protective embrace or cozy cuddle', 'A traditional wooden cup', 'A rainy morning walk', 'A friendly neighborly greeting'],
    correctAnswer: 'A loving, protective embrace or cozy cuddle',
    explanation: '"Cwtch" is a magical Welsh word meaning a warm, safe hug that makes all worries fade away.',
    active: true,
  },
  {
    id: 'gw-9',
    category: 'guess_word',
    countryCode: 'KR',
    countryName: 'South Korea',
    difficulty: 'hard',
    prompt: 'In Korean social intuition, what does "눈치" (Nunchi) refer to?',
    options: ['The subtle art of reading moods and atmosphere in a room', 'Eye contact with elders', 'Patience while waiting in queue', 'Bowing respectfully'],
    correctAnswer: 'The subtle art of reading moods and atmosphere in a room',
    explanation: '"Nunchi" (눈치) is quick, perceptive social intelligence: gauging someone’s mood, thoughts, and unspoken feelings.',
    active: true,
  },
  {
    id: 'gw-10',
    category: 'guess_word',
    countryCode: 'EG',
    countryName: 'Egypt',
    difficulty: 'easy',
    prompt: 'In Egyptian colloquial Arabic, what does the warm welcoming phrase "نَوَّرْت" (Nawwart) mean?',
    options: ['You have brought light into our home/presence', 'Have a pleasant trip', 'Good morning to you', 'Let us eat dinner'],
    correctAnswer: 'You have brought light into our home/presence',
    explanation: '"Nawwart" literally translates to "You illuminated us," spoken warmly whenever a welcome guest arrives.',
    active: true,
  },

  // ==========================================
  // MINI-GAME 3: MYSTERY FOOD
  // ==========================================
  {
    id: 'mf-1',
    category: 'mystery_food',
    countryCode: 'TN',
    countryName: 'Tunisia',
    difficulty: 'easy',
    prompt: 'Which country is celebrated for spicy Couscous with seafood/grouper and crispy deep-fried "Brik à l’oeuf" pastry?',
    options: ['Tunisia', 'Jordan', 'Lebanon', 'Greece'],
    correctAnswer: 'Tunisia',
    explanation: 'Tunisian couscous is uniquely prepared with rich tomato sauce and spicy Harissa, often topped with fresh Mediterranean fish or lamb.',
    active: true,
  },
  {
    id: 'mf-2',
    category: 'mystery_food',
    countryCode: 'JP',
    countryName: 'Japan',
    difficulty: 'easy',
    prompt: 'Steaming wheat noodles served in savory pork/soy/miso broth topped with chashu pork, nori, and soft-boiled egg is:',
    options: ['Ramen (Japan)', 'Pho (Vietnam)', 'Laksa (Malaysia)', 'Japchae (Korea)'],
    correctAnswer: 'Ramen (Japan)',
    explanation: 'Ramen is a beloved Japanese staple noodle dish with deeply flavorful broths perfected over decades in regional shops.',
    active: true,
  },
  {
    id: 'mf-3',
    category: 'mystery_food',
    countryCode: 'BR',
    countryName: 'Brazil',
    difficulty: 'medium',
    prompt: '"Feijoada", a hearty black bean stew simmered with smoked pork, served with white rice and orange slices, is the national dish of:',
    options: ['Brazil', 'Cuba', 'Argentina', 'Portugal'],
    correctAnswer: 'Brazil',
    explanation: 'Feijoada is regarded as Brazil’s national dish, traditionally savored on weekends accompanied by farofa and samba music.',
    active: true,
  },
  {
    id: 'mf-4',
    category: 'mystery_food',
    countryCode: 'MX',
    countryName: 'Mexico',
    difficulty: 'easy',
    prompt: 'Corn tortillas filled with spit-roasted marinated pork, cilantro, diced onion, and a slice of grilled pineapple describe:',
    options: ['Tacos al Pastor (Mexico)', 'Pupusas (El Salvador)', 'Arepas (Venezuela)', 'Empanadas (Argentina)'],
    correctAnswer: 'Tacos al Pastor (Mexico)',
    explanation: 'Tacos al Pastor is an iconic Mexican street food creation influenced by Lebanese immigrants adapting shawarma spit-roasting in Mexico City.',
    active: true,
  },
  {
    id: 'mf-5',
    category: 'mystery_food',
    countryCode: 'ES',
    countryName: 'Spain',
    difficulty: 'easy',
    prompt: 'A saffron-infused rice dish cooked in a wide shallow pan with rabbit, chicken, green beans, or fresh seafood is:',
    options: ['Paella (Spain)', 'Risotto (Italy)', 'Biryani (India)', 'Jambalaya (USA)'],
    correctAnswer: 'Paella (Spain)',
    explanation: 'Paella originates in Valencia, Spain, where socarrat (the crispy caramelized bottom crust of rice) is prized as the best bite.',
    active: true,
  },
  {
    id: 'mf-6',
    category: 'mystery_food',
    countryCode: 'KR',
    countryName: 'South Korea',
    difficulty: 'easy',
    prompt: '"Bibimbap", a colorful bowl of warm rice topped with sautéed seasoned vegetables, gochujang, and an egg, is from:',
    options: ['South Korea', 'China', 'Thailand', 'Vietnam'],
    correctAnswer: 'South Korea',
    explanation: 'Bibimbap literally translates to "mixed rice" and represents harmonic balance in Korean cuisine through diverse vibrant colors.',
    active: true,
  },
  {
    id: 'mf-7',
    category: 'mystery_food',
    countryCode: 'IT',
    countryName: 'Italy',
    difficulty: 'easy',
    prompt: 'A thin-crust pizza topped with San Marzano tomatoes, fresh mozzarella, basil, and extra virgin olive oil represents the Italian flag. It is called:',
    options: ['Pizza Margherita', 'Pizza Marinara', 'Pizza Quattro Stagioni', 'Pizza Diavola'],
    correctAnswer: 'Pizza Margherita',
    explanation: 'Pizza Margherita was crafted in Naples in 1889 to honor Queen Margherita of Savoy, mimicking the red, white, and green of Italy’s flag.',
    active: true,
  },
  {
    id: 'mf-8',
    category: 'mystery_food',
    countryCode: 'NG',
    countryName: 'Nigeria',
    difficulty: 'medium',
    prompt: 'Long-grain rice simmered in a spiced puree of bell peppers, scotch bonnets, tomatoes, and onions is the pride of West Africa, especially:',
    options: ['Jollof Rice (Nigeria)', 'Biryani (Pakistan)', 'Mansaf (Jordan)', 'Pilau (Tanzania)'],
    correctAnswer: 'Jollof Rice (Nigeria)',
    explanation: 'Nigerian Jollof Rice is renowned for its signature smoky aroma achieved through simmering over firewood at lively celebrations.',
    active: true,
  },
  {
    id: 'mf-9',
    category: 'mystery_food',
    countryCode: 'CA',
    countryName: 'Canada',
    difficulty: 'easy',
    prompt: 'Hot crispy french fries crowned with fresh squeaky cheese curds and smothered in rich brown gravy is known as:',
    options: ['Poutine (Canada)', 'Fish & Chips (UK)', 'Loaded Fries (USA)', 'Chips Mayonnaise (Belgium)'],
    correctAnswer: 'Poutine (Canada)',
    explanation: 'Poutine originated in rural Quebec diners in the late 1950s and has grown into a beloved symbol of Canadian comfort food.',
    active: true,
  },
  {
    id: 'mf-10',
    category: 'mystery_food',
    countryCode: 'PE',
    countryName: 'Peru',
    difficulty: 'medium',
    prompt: 'Raw cubes of fresh ocean fish cured in freshly squeezed key lime juice with sliced red onion, rocoto chili, and sweet potato is:',
    options: ['Ceviche (Peru)', 'Poke (Hawaii)', 'Carpaccio (Italy)', 'Gravlax (Sweden)'],
    correctAnswer: 'Ceviche (Peru)',
    explanation: 'Ceviche is Peru’s declared national heritage dish, prized for the "Leche de Tigre" (tiger’s milk) marinade that cures the fish.',
    active: true,
  },

  // ==========================================
  // MINI-GAME 4: MUSIC & CULTURE
  // ==========================================
  {
    id: 'mc-1',
    category: 'music_culture',
    countryCode: 'TN',
    countryName: 'Tunisia',
    difficulty: 'medium',
    prompt: 'Which pear-shaped string instrument with 11 or 13 strings is the sovereign centerpiece of Arabic and Tunisian Malouf classical music?',
    options: ['Oud (عُود)', 'Sitar', 'Bouzouki', 'Balalaika'],
    correctAnswer: 'Oud (عُود)',
    explanation: 'The Oud is revered across North Africa and the Middle East as the "King of Instruments", providing the melodic soul of Maqam music.',
    audioNote: 'oud_arpeggio',
    active: true,
  },
  {
    id: 'mc-2',
    category: 'music_culture',
    countryCode: 'IN',
    countryName: 'India',
    difficulty: 'easy',
    prompt: 'Which plucked string instrument with sympathetic drone strings was popularized internationally by master musician Ravi Shankar?',
    options: ['Sitar', 'Koto', 'Banjo', 'Shamisen'],
    correctAnswer: 'Sitar',
    explanation: 'The Sitar is a classical Hindustani instrument renowned for its resonant gourd, curved frets, and shimmering microtonal bends.',
    audioNote: 'sitar_drone',
    active: true,
  },
  {
    id: 'mc-3',
    category: 'music_culture',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    difficulty: 'easy',
    prompt: 'The Great Highland Bagpipe is an iconic musical instrument deeply associated with which historic Celtic nation?',
    options: ['Scotland', 'Ireland', 'Cornwall', 'Isle of Man'],
    correctAnswer: 'Scotland',
    explanation: 'The Great Highland bagpipe was used by Scottish Highland clans for military gatherings, ceremonies, and spirited Ceilidhs.',
    audioNote: 'bagpipe_drone',
    active: true,
  },
  {
    id: 'mc-4',
    category: 'music_culture',
    countryCode: 'AU',
    countryName: 'Australia',
    difficulty: 'medium',
    prompt: 'The Didgeridoo (Yidaki), a wind instrument made from natural eucalyptus hollowed by termites, was developed by Indigenous peoples of:',
    options: ['Australia', 'New Zealand', 'Papua New Guinea', 'Fiji'],
    correctAnswer: 'Australia',
    explanation: 'The Didgeridoo has been played by Aboriginal Australians for thousands of years, utilizing circular breathing to produce deep resonant drones.',
    audioNote: 'didgeridoo_rumble',
    active: true,
  },
  {
    id: 'mc-5',
    category: 'music_culture',
    countryCode: 'BR',
    countryName: 'Brazil',
    difficulty: 'easy',
    prompt: 'Which gentle lyrical fusion of Samba and Cool Jazz originated in Rio de Janeiro in the late 1950s (e.g. "The Girl from Ipanema")?',
    options: ['Bossa Nova', 'Tango', 'Reggaeton', 'Merengue'],
    correctAnswer: 'Bossa Nova',
    explanation: 'Bossa Nova ("new wave") was pioneered by João Gilberto, Antônio Carlos Jobim, and Vinicius de Moraes.',
    audioNote: 'bossa_chords',
    active: true,
  },
  {
    id: 'mc-6',
    category: 'music_culture',
    countryCode: 'JP',
    countryName: 'Japan',
    difficulty: 'medium',
    prompt: 'Dynamic ensemble drumming performances featuring thunderous barrel-shaped wooden drums in Japan are known as:',
    options: ['Taiko (太鼓)', 'Gamelan', 'Djembe', 'Bongos'],
    correctAnswer: 'Taiko (太鼓)',
    explanation: 'Taiko drumming combines powerful athletic movement, precise synchronicity, and deep resonant beats rooted in Shinto festivals.',
    audioNote: 'taiko_strike',
    active: true,
  },
  {
    id: 'mc-7',
    category: 'music_culture',
    countryCode: 'MX',
    countryName: 'Mexico',
    difficulty: 'easy',
    prompt: 'Ensembles featuring violins, trumpets, vihuelas, guitarróns, and performers in charro suits are the hallmark of Mexican:',
    options: ['Mariachi', 'Flamenco', 'Ranchera Solo', 'Cumbia Son'],
    correctAnswer: 'Mariachi',
    explanation: 'Mariachi music is recognized by UNESCO as intangible cultural heritage, playing celebratory songs at birthdays, weddings, and plazas.',
    audioNote: 'mariachi_fanfare',
    active: true,
  },
  {
    id: 'mc-8',
    category: 'music_culture',
    countryCode: 'NG',
    countryName: 'Nigeria',
    difficulty: 'medium',
    prompt: 'Which revolutionary West African musical genre blending jazz, funk, highlife, and Yoruba percussion was pioneered by Fela Kuti in Lagos?',
    options: ['Afrobeat', 'Kwaito', 'Highlife Solo', 'Kizomba'],
    correctAnswer: 'Afrobeat',
    explanation: 'Fela Kuti created Afrobeat in the 1970s at his Afrika Shrine in Lagos, combining infectious rhythmic grooves with social commentary.',
    audioNote: 'afrobeat_groove',
    active: true,
  },

  // ==========================================
  // MINI-GAME 5: WORLD MAP
  // ==========================================
  {
    id: 'wm-1',
    category: 'world_map',
    countryCode: 'TN',
    countryName: 'Tunisia',
    difficulty: 'medium',
    prompt: 'Spot Tunisia on the Mediterranean coast of North Africa!',
    options: ['Tunisia (North Africa)', 'Egypt (Northeast Africa)', 'Morocco (West North Africa)', 'Algeria (Central North Africa)'],
    correctAnswer: 'Tunisia (North Africa)',
    targetCountryCode: 'TN',
    explanation: 'Tunisia occupies the northernmost tip of the African continent, jutting out toward Sicily and the central Mediterranean.',
    active: true,
  },
  {
    id: 'wm-2',
    category: 'world_map',
    countryCode: 'JP',
    countryName: 'Japan',
    difficulty: 'easy',
    prompt: 'Locate the Pacific island archipelago of Japan in East Asia!',
    options: ['Japan (East Asia)', 'Philippines (Southeast Asia)', 'South Korea (Korean Peninsula)', 'Taiwan (East Asia)'],
    correctAnswer: 'Japan (East Asia)',
    targetCountryCode: 'JP',
    explanation: 'Japan forms a distinctive crescent archipelago along the eastern coast of the Asian continent.',
    active: true,
  },
  {
    id: 'wm-3',
    category: 'world_map',
    countryCode: 'BR',
    countryName: 'Brazil',
    difficulty: 'easy',
    prompt: 'Identify the largest nation in South America, spanning the Amazon basin and Atlantic coast!',
    options: ['Brazil (South America)', 'Argentina (Southern Cone)', 'Colombia (Northwest SA)', 'Peru (West SA)'],
    correctAnswer: 'Brazil (South America)',
    targetCountryCode: 'BR',
    explanation: 'Brazil borders nearly every nation in South America (except Chile and Ecuador) and dominates the eastern half of the continent.',
    active: true,
  },
  {
    id: 'wm-4',
    category: 'world_map',
    countryCode: 'FR',
    countryName: 'France',
    difficulty: 'easy',
    prompt: 'Find France, situated between the English Channel, Atlantic Ocean, and Mediterranean Sea in Western Europe!',
    options: ['France (Western Europe)', 'Spain (Iberian Peninsula)', 'Germany (Central Europe)', 'United Kingdom (British Isles)'],
    correctAnswer: 'France (Western Europe)',
    targetCountryCode: 'FR',
    explanation: 'France connects Northern Europe with the Mediterranean world through its central western European location.',
    active: true,
  },
  {
    id: 'wm-5',
    category: 'world_map',
    countryCode: 'EG',
    countryName: 'Egypt',
    difficulty: 'easy',
    prompt: 'Locate Egypt, the transcontinental crossroads connecting Northeast Africa with the Sinai Peninsula and Asia!',
    options: ['Egypt (Northeast Africa)', 'Libya (North Africa)', 'Saudi Arabia (Middle East)', 'Sudan (East Africa)'],
    correctAnswer: 'Egypt (Northeast Africa)',
    targetCountryCode: 'EG',
    explanation: 'Egypt controls the historic Suez Canal linking the Mediterranean Sea to the Red Sea.',
    active: true,
  },
  {
    id: 'wm-6',
    category: 'world_map',
    countryCode: 'AU',
    countryName: 'Australia',
    difficulty: 'easy',
    prompt: 'Spot the island continent of Australia surrounded by the Indian and Pacific Oceans in the Southern Hemisphere!',
    options: ['Australia (Oceania)', 'New Zealand (Oceania)', 'Indonesia (Southeast Asia)', 'Madagascar (Indian Ocean)'],
    correctAnswer: 'Australia (Oceania)',
    targetCountryCode: 'AU',
    explanation: 'Australia lies entirely south of the equator between latitudes 10°S and 44°S.',
    active: true,
  },

  // ==========================================
  // MINI-GAME 6: CULTURAL MIME & TRADITIONS
  // ==========================================
  {
    id: 'cm-1',
    category: 'cultural_mime',
    countryCode: 'JP',
    countryName: 'Japan',
    difficulty: 'easy',
    prompt: '🌸 Gathering under blooming cherry blossom trees with family and friends to share food, drinks, and admire spring petals is the tradition of:',
    options: ['Hanami (Japan)', 'Songkran (Thailand)', 'Chuseok (Korea)', 'Qingming (China)'],
    correctAnswer: 'Hanami (Japan)',
    explanation: '"Hanami" (flower viewing) dates back over a thousand years, celebrating the fleeting beauty of Sakura blooms as a symbol of life.',
    active: true,
  },
  {
    id: 'cm-2',
    category: 'cultural_mime',
    countryCode: 'ES',
    countryName: 'Spain',
    difficulty: 'easy',
    prompt: '🍅 An exuberant festival held every August in the town of Buñol where participants engage in a massive, friendly overripe tomato battle is:',
    options: ['La Tomatina (Spain)', 'Carnevale (Italy)', 'San Fermín (Spain)', 'Fallas de Valencia (Spain)'],
    correctAnswer: 'La Tomatina (Spain)',
    explanation: 'La Tomatina draws thousands of travelers to Buñol to fling over 150 metric tons of crushed tomatoes in pure playful celebration.',
    active: true,
  },
  {
    id: 'cm-3',
    category: 'cultural_mime',
    countryCode: 'MX',
    countryName: 'Mexico',
    difficulty: 'easy',
    prompt: '💀 Building candlelit ofrendas adorned with cempasúchil (marigolds), sugar calaveras, and pan de muerto to welcome departed spirits is:',
    options: ['Día de los Muertos (Mexico)', 'Halloween (USA)', 'Inti Raymi (Peru)', 'Guelaguetza (Mexico)'],
    correctAnswer: 'Día de los Muertos (Mexico)',
    explanation: 'Day of the Dead is a heartwarming, joyous Mexican celebration where families welcome the souls of deceased loved ones for reunion.',
    active: true,
  },
  {
    id: 'cm-4',
    category: 'cultural_mime',
    countryCode: 'TH',
    countryName: 'Thailand',
    difficulty: 'easy',
    prompt: '💦 Joyful nationwide celebrations marking the New Year with water guns, buckets, and sprinkling water to wash away bad luck is:',
    options: ['Songkran (Thailand)', 'Loy Krathong (Thailand)', 'Holi (India)', 'Lantern Festival (Taiwan)'],
    correctAnswer: 'Songkran (Thailand)',
    explanation: 'Songkran marks the Buddhist solar new year in April, transforming the streets of Bangkok and Chiang Mai into friendly water festivities.',
    active: true,
  },
  {
    id: 'cm-5',
    category: 'cultural_mime',
    countryCode: 'IN',
    countryName: 'India',
    difficulty: 'easy',
    prompt: '🎨 Tossing vibrantly colored gulal powders into the air, dancing to dhol drums, and welcoming spring renewal is the Hindu festival of:',
    options: ['Holi (India)', 'Diwali (India)', 'Navratri (India)', 'Onam (India)'],
    correctAnswer: 'Holi (India)',
    explanation: 'Holi is the legendary festival of colors, signifying the arrival of spring, forgiveness, and the triumph of good over evil.',
    active: true,
  },
  {
    id: 'cm-6',
    category: 'cultural_mime',
    countryCode: 'TN',
    countryName: 'Tunisia',
    difficulty: 'medium',
    prompt: '🌿 The ceremonial application of intricate floral patterns on hands during the pre-wedding "Wtiya" night in Tunisia uses which natural paste?',
    options: ['Henna (الحناء)', 'Indigo', 'Kohl', 'Saffron'],
    correctAnswer: 'Henna (الحناء)',
    explanation: 'The Henna night (El Henna / El Wtiya) is an ancient North African celebratory bridal tradition wishing joy, beauty, and protection.',
    active: true,
  },

  // ==========================================
  // MINI-GAME 7: 1 VS 1 DUEL (HIGH SPEED)
  // ==========================================
  {
    id: 'dl-1',
    category: 'duel',
    countryCode: 'JP',
    countryName: 'Japan',
    difficulty: 'easy',
    prompt: 'FAST BUZZER: Which country’s flag consists of a pure white background with a single solid red circle in the center?',
    options: ['Japan', 'Bangladesh', 'Palau', 'South Korea'],
    correctAnswer: 'Japan',
    explanation: 'The Hinomaru ("Circle of the Sun") has been an official Japanese naval and state ensign since 1870.',
    active: true,
  },
  {
    id: 'dl-2',
    category: 'duel',
    countryCode: 'TN',
    countryName: 'Tunisia',
    difficulty: 'easy',
    prompt: 'FAST BUZZER: Which North African country features a red field with a white central disc containing a red crescent and five-pointed star?',
    options: ['Tunisia', 'Turkey', 'Algeria', 'Libya'],
    correctAnswer: 'Tunisia',
    explanation: 'Adopted in 1827 by Al-Husayn II ibn Mahmud, the flag of Tunisia is one of the oldest national flags still in continuous use.',
    active: true,
  },
  {
    id: 'dl-3',
    category: 'duel',
    countryCode: 'FR',
    countryName: 'France',
    difficulty: 'easy',
    prompt: 'FAST BUZZER: What are the three vertical colors of the French national tricolor flag from hoist to fly?',
    options: ['Blue, White, Red', 'Red, White, Blue', 'Green, White, Red', 'Blue, Yellow, Red'],
    correctAnswer: 'Blue, White, Red',
    explanation: 'The French Tricolore represents the historic colors of Paris (Blue & Red) alongside the Royal White of the monarchy.',
    active: true,
  },
  {
    id: 'dl-4',
    category: 'duel',
    countryCode: 'BR',
    countryName: 'Brazil',
    difficulty: 'easy',
    prompt: 'FAST BUZZER: What Portuguese motto is inscribed across the celestial globe on Brazil’s flag?',
    options: ['Ordem e Progresso (Order and Progress)', 'Liberdade e Paz (Liberty and Peace)', 'União e Força (Union and Strength)', 'Patria Amada (Beloved Homeland)'],
    correctAnswer: 'Ordem e Progresso (Order and Progress)',
    explanation: '"Ordem e Progresso" was inspired by Auguste Comte’s positivist motto: "Love as a principle and order as the basis; progress as the goal".',
    active: true,
  },
  {
    id: 'dl-5',
    category: 'duel',
    countryCode: 'IT',
    countryName: 'Italy',
    difficulty: 'easy',
    prompt: 'FAST BUZZER: Which European capital city was historically built across seven legendary hills including the Palatine and Capitoline?',
    options: ['Rome', 'Athens', 'Madrid', 'Vienna'],
    correctAnswer: 'Rome',
    explanation: 'Rome is famously known as the City of the Seven Hills (Sette Colli di Roma).',
    active: true,
  }
];

export function getQuestionsByCategory(category: GameCategory, limit: number = 5): Question[] {
  const filtered = QUESTIONS.filter((q) => q.category === category);
  return shuffleArray(filtered).slice(0, limit);
}

export function getRandomQuestions(count: number = 5): Question[] {
  return shuffleArray([...QUESTIONS]).slice(0, count);
}

function shuffleArray<T>(arr: T[]): T[] {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}
